import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bespokeSerif = localFont({
  src: [
    {
      path: "../public/fonts/bespoke-serif/BespokeSerif-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/bespoke-serif/BespokeSerif-LightItalic.woff2",
      weight: "300",
      style: "italic",
    },
    {
      path: "../public/fonts/bespoke-serif/BespokeSerif-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/bespoke-serif/BespokeSerif-Italic.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "../public/fonts/bespoke-serif/BespokeSerif-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/bespoke-serif/BespokeSerif-MediumItalic.woff2",
      weight: "500",
      style: "italic",
    },
    {
      path: "../public/fonts/bespoke-serif/BespokeSerif-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/bespoke-serif/BespokeSerif-BoldItalic.woff2",
      weight: "700",
      style: "italic",
    },
    {
      path: "../public/fonts/bespoke-serif/BespokeSerif-Extrabold.woff2",
      weight: "800",
      style: "normal",
    },
    {
      path: "../public/fonts/bespoke-serif/BespokeSerif-ExtraboldItalic.woff2",
      weight: "800",
      style: "italic",
    },
  ],
  variable: "--font-bespoke-serif",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { AuthProvider } from "@/context/AuthContext";

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${bespokeSerif.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
