"""add link model and total visits

Revision ID: 1b0e9d41900e
Revises: 88f633a0e961
Create Date: 2026-09-23 16:00:55.106369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b0e9d41900e'
down_revision: Union[str, Sequence[str], None] = '88f633a0e961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('shortcode', sa.String(), nullable=False),
    sa.Column('total_clicks', sa.Integer(), nullable=True),
    sa.Column('total_scans', sa.Integer(), nullable=True),
    sa.Column('total_lead_captures', sa.Integer(), nullable=True),
    sa.Column('qr_config', sa.JSON(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('platform_content_id', sa.String(), nullable=True),
    sa.Column('platform_views', sa.Integer(), nullable=True),
    sa.Column('platform_stats', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('page_id IS NOT NULL OR campaign_id IS NOT NULL', name='check_page_or_campaign_present'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_links_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_links_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_links_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_links_page_id'), ['page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_links_shortcode'), ['shortcode'], unique=True)
        batch_op.create_index(batch_op.f('ix_links_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_visits', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_lead_captures', sa.Integer(), nullable=True))

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_visits', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_lead_captures', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_column('total_lead_captures')
        batch_op.drop_column('total_visits')

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_column('total_lead_captures')
        batch_op.drop_column('total_visits')

    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_links_user_id'))
        batch_op.drop_index(batch_op.f('ix_links_shortcode'))
        batch_op.drop_index(batch_op.f('ix_links_page_id'))
        batch_op.drop_index(batch_op.f('ix_links_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_links_id'))
        batch_op.drop_index(batch_op.f('ix_links_campaign_id'))

    op.drop_table('links')
    # ### end Alembic commands ###
