"""Add subscription and payment models

Revision ID: ac653077bc26
Revises: c8d442aba6e1
Create Date: 2026-09-22 16:12:04.411000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac653077bc26'
down_revision: Union[str, Sequence[str], None] = 'c8d442aba6e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_features_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_features_name'), ['name'], unique=True)

    op.create_table('subscription_plans',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_plans_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_plans_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_plans_name'), ['name'], unique=True)

    op.create_table('payment_history',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('cashfree_order_id', sa.String(), nullable=True),
    sa.Column('cashfree_payment_id', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_history_cashfree_order_id'), ['cashfree_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_history_cashfree_payment_id'), ['cashfree_payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_history_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_history_user_id'), ['user_id'], unique=False)

    op.create_table('plan_features',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('feature_id', sa.UUID(), nullable=False),
    sa.Column('limit_value', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_features_id'), ['id'], unique=False)

    op.create_table('user_subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_subscriptions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_subscriptions_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_subscriptions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('user_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_subscriptions_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_user_subscriptions_id'))

    op.drop_table('user_subscriptions')
    with op.batch_alter_table('plan_features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_features_id'))

    op.drop_table('plan_features')
    with op.batch_alter_table('payment_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_payment_history_id'))
        batch_op.drop_index(batch_op.f('ix_payment_history_cashfree_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payment_history_cashfree_order_id'))

    op.drop_table('payment_history')
    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_plans_name'))
        batch_op.drop_index(batch_op.f('ix_subscription_plans_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_subscription_plans_id'))

    op.drop_table('subscription_plans')
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_features_name'))
        batch_op.drop_index(batch_op.f('ix_features_id'))

    op.drop_table('features')
    # ### end Alembic commands ###
